"""Init

Revision ID: 3a1f2f188b95
Revises: 
Create Date: 2025-02-07 15:39:54.032870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1f2f188b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tron_wallet_requests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tron_wallet_requests')
    # ### end Alembic commands ###
